[package]
name = "montyc_ast"
version = "0.0.0"
edition = "2021"

[dependencies]
montyc_lexer = { path = "../montyc_lexer" }
montyc_core = { path = "../montyc_core" }

serde = { version = "1.0.147", features = ["derive"] }
