[package]
name = "montyc"
version = "0.99.0"
authors = ["mental <mentalfoss@gmail.com>"]
edition = "2018"
description = "A Strongly Typed, Flexible, and Compiled Python Dialect"
documentation = "https://docs.rs/montyc"
readme = "README.md"
repository = "https://github.com/mental32/monty"
license = "MIT"
keyword = ["compilers", "typecheckers", "monty", "python"]

[dependencies]
montyc_parser = { path = "../montyc_parser" }
montyc_core = { path = "../montyc_core" }
montyc_hlir = { path = "../montyc_hlir" }

# "make my life easier" dependencies
# derive_more = "0.99.13"
structopt = "0.3.21"
# thiserror = "1.0.24"
# dashmap = "4.0.2"

petgraph = "0.5.1"


# Logging dependencies
log = "0.4.14"
env_logger = "0.8.3"

# # codegen dependencies
cranelift-codegen = "0.73.0"
# cranelift-frontend = "0.73.0"
# cranelift-object = "0.73.0"
# cranelift-module = "0.73.0"
target-lexicon = "0.12.0"
ahash = { version = "0.7.4", features = ["std"] }
# tempfile = "3.2.0"

# # error reporting
# codespan = "0.11.1"
# codespan-reporting = "0.11.1"
