# DO NOT EDIT THIS FILE: automatically generated from 'magic.py' in the repository root.

id
int
float
tuple
object
dict
set
type
list
str
bool
isinstance
__add__  # type: ignore
__radd__  # type: ignore
__mul__  # type: ignore
__rmul__  # type: ignore
__getattr__  # type: ignore
__rgetattr__  # type: ignore
__div__  # type: ignore
__rdiv__  # type: ignore
__or__  # type: ignore
__ror__  # type: ignore
__eq__  # type: ignore
__req__  # type: ignore
__getattribute__  # type: ignore
__rgetattribute__  # type: ignore
__and__  # type: ignore
__rand__  # type: ignore
__ne__  # type: ignore
__rne__  # type: ignore
__sub__  # type: ignore
__rsub__  # type: ignore
__rshift__  # type: ignore
__rrshift__  # type: ignore
__lshift__  # type: ignore
__rlshift__  # type: ignore
__call__  # type: ignore
__rcall__  # type: ignore
__pow__  # type: ignore
__rpow__  # type: ignore
__getitem__  # type: ignore
__rgetitem__  # type: ignore
__iter__  # type: ignore
__next__  # type: ignore
__eq__  # type: ignore
__len__  # type: ignore
__call__  # type: ignore
c_long  # type: ignore
c_long_p # type: ignore
c_wchar  # type: ignore
c_wchar_p # type: ignore
c_ubyte  # type: ignore
c_ubyte_p # type: ignore
c_int8  # type: ignore
c_int8_p # type: ignore
c_int64  # type: ignore
c_int64_p # type: ignore
c_ushort  # type: ignore
c_ushort_p # type: ignore
c_uint64  # type: ignore
c_uint64_p # type: ignore
c_void  # type: ignore
c_void_p # type: ignore
c_float  # type: ignore
c_float_p # type: ignore
c_uint16  # type: ignore
c_uint16_p # type: ignore
c_uint  # type: ignore
c_uint_p # type: ignore
c_ulonglong  # type: ignore
c_ulonglong_p # type: ignore
c_double  # type: ignore
c_double_p # type: ignore
c_uint32  # type: ignore
c_uint32_p # type: ignore
c_size_t  # type: ignore
c_size_t_p # type: ignore
c_ssize_t  # type: ignore
c_ssize_t_p # type: ignore
c_int32  # type: ignore
c_int32_p # type: ignore
c_int  # type: ignore
c_int_p # type: ignore
c_longlong  # type: ignore
c_longlong_p # type: ignore
c_uint8  # type: ignore
c_uint8_p # type: ignore
c_byte  # type: ignore
c_byte_p # type: ignore
c_char  # type: ignore
c_char_p # type: ignore
c_ulong  # type: ignore
c_ulong_p # type: ignore
c_bool  # type: ignore
c_bool_p # type: ignore
c_longdouble  # type: ignore
c_longdouble_p # type: ignore
__value  # type: ignore
