# DO NOT EDIT THIS FILE: automatically generated from 'magic.py' in the repository root.

float
str
int
__mul__
__rmul__
__add__
__radd__
__eq__
__and__
__rand__
__lshift__
__rlshift__
__or__
__ror__
__pow__
__rpow__
__rshift__
__rrshift__
__sub__
__rsub__
