[workspace]
members = ["montyc", "montyc_parser", "montyc_core", "montyc_hlir", "montyc_codegen"]

[profile.dev]
codegen-units = 8
lto = "off"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
debug-assertions = false
debug = 0
