[package]
name = "montyc_flatcode"
version = "0.99.0"
edition = "2021"

[dependencies]
montyc_core_types = { path = "../montyc_core_types" }
montyc_parser = { path = "../montyc_parser" }
montyc_lexer = { path = "../montyc_lexer" }
montyc_ast = { path = "../montyc_ast" }
