[package]
name = "montyc_parser"
version = "0.0.0"
edition = "2021"

[dependencies]
montyc_lexer = { path = "../montyc_lexer" }
montyc_query = { path = "../montyc_query" }

ariadne = "0.1.5"
chumsky = "0.8.0"
