[package]
name = "montyc_core"
version = "0.99.0"
edition = "2018"

[dependencies]
montyc_lexer = { path = "../montyc_lexer" }

thiserror = "1.0.25"
derive_more = "0.99"
ahash = "0.7.4"
petgraph = "0.6.0"
structopt = "0.3.21"
